include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/meizu/FTS3AD54/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/meizu/

obj-y	+=  fts.o
obj-y	+=  fts_dev.o
